version: '3.8'

x-logging-defaults:
  &logging-defaults
  logging:
    options:
      max-size: 5m

services:

  # RavenDB
  ravendb:
    <<: *logging-defaults
    image: ravendb/ravendb:6.2-ubuntu-latest
    ports:
      - "32921:8080"
    volumes:
      - ravendb-data:/opt/RavenDB/Server/RavenData
      - ravendb-conf:/opt/RavenDB/config
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork

volumes:
  ravendb-data:
  ravendb-conf:
 